# Notebook using ```scrutins_complete.csv```: introduction, descriptives statititics and more...

### 1. Data

In [34]:
import pandas as pd

# Load with low_memory=False to avoid mixed type warnings
df = pd.read_csv('scrutins_complete.csv', low_memory=False)
print(df.shape)
df.head()

(2043131, 48)

,scrutin_id,acteur_id,acteur_id_merge,mandat_id,seance_id,groupe_id,depute_nom_complet,ident_civ_ANM,ident_prenom_ANM,ident_nom_ANM,...,groupe_nb_contre,groupe_nb_abs,groupe_nb_volnonvotant,groupe_codetype_ANO,groupe_abrege_ANO,groupe_libelle_ANO,acteur_id_mandats,mandat_id_mandats,mandat_annee_debut_ANM,mandat_annee_fin_ANM
0,VTANR5L14V1,PA328,PA0328,PM645184,RUANR5L14S2012IDS16433,PO656002,Jean-Marc Ayrault,M.,Jean-Marc,Ayrault,...,0.0,NaN,NaN,GP,SRC,"Socialiste, républicain et citoyen",PA328,PM266864,2002.0,2007.0
1,VTANR5L14V1,PA381,PA0381,PM645125,RUANR5L14S2012IDS16433,PO656002,Claude Bartolone,M.,Claude,Bartolone,...,0.0,NaN,NaN,GP,SRC,"Socialiste, républicain et citoyen",PA381,PM682604,2012.0,2017.0
2,VTANR5L14V1,PA1268,PA1268,PM645112,RUANR5L14S2012IDS16433,PO656002,Laurent Fabius,M.,Laurent,Fabius,...,0.0,NaN,NaN,GP,SRC,"Socialiste, républicain et citoyen",PA1268,PM267232,2002.0,2007.0
3,VTANR5L14V1,PA2912,PA2912,PM645085,RUANR5L14S2012IDS16433,PO656002,Alain Vidalies,M.,Alain,Vidalies,...,0.0,NaN,NaN,GP,SRC,"Socialiste, républicain et citoyen",PA2912,PM267483,2002.0,2007.0
4,VTANR5L14V1,PA1816,PA1816,PM645051,RUANR5L14S2012IDS16433,PO656002,François Lamy,M.,François,Lamy,...,0.0,NaN,NaN,GP,SRC,"Socialiste, républicain et citoyen",PA1816,PM267937,2002.0,2007.0

### Pour alléger et parce que l'étude porte sur la période 2014-2024, on enlève tous les votes antérieurs à 2014

In [35]:
# Filter: keep only votes from 2014 to 2024
print(df.shape[0])
old = df.shape[0]
df = df[(df['scrutin_date'] >= '2014-01-01') & ('2024-12-31' >= df['scrutin_date'])]
print(f"After filtering (>= 2014): {df.shape[0]:,} rows. We drop {(old - df.shape[0]):,} rows")
df.sort_values('scrutin_date', ascending=True)["scrutin_date"].head()

2043131
After filtering (>= 2014): 1,249,688 rows. We drop 793,443 rows

37310    2014-01-07
37311    2014-01-07
37312    2014-01-07
37313    2014-01-08
37314    2014-01-08
Name: scrutin_date, dtype: object

#### Quelques statistiques descriptives sur les votants.

In [36]:
df.columns.to_list()

['scrutin_id',
 'acteur_id',
 'acteur_id_merge',
 'mandat_id',
 'seance_id',
 'groupe_id',
 'depute_nom_complet',
 'ident_civ_ANM',
 'ident_prenom_ANM',
 'ident_nom_ANM',
 'ident_male_ANM',
 'ident_year_birth_ANM',
 'profession_libellecourant_ANM',
 'election_lieu_departement_ANM',
 'election_lieu_numcirco_ANM',
 'mandat_legislature_ANM',
 'acteur_vote',
 'scrutin_legislature',
 'scrutin_date',
 'scrutin_jour_seance',
 'scrutin_type_code',
 'scrutin_type_majorite',
 'scrutin_resultat',
 'scrutin_titre',
 'scrutin_objet',
 'scrutin_nb_votants',
 'scrutin_nb_suffrages',
 'scrutin_nb_requis',
 'scrutin_annonce',
 'scrutin_nb_nonvotants',
 'scrutin_nb_pour',
 'scrutin_nb_contre',
 'scrutin_nb_abs',
 'scrutin_nb_volnonvotant',
 'groupe_nb_membres',
 'groupe_pos_maj',
 'groupe_nb_nonvotant',
 'groupe_nb_pour',
 'groupe_nb_contre',
 'groupe_nb_abs',
 'groupe_nb_volnonvotant',
 'groupe_codetype_ANO',
 'groupe_abrege_ANO',
 'groupe_libelle_ANO',
 'acteur_id_mandats',
 'mandat_id_mandats',
 'mandat_annee_debut_ANM',
 'mandat_annee_fin_ANM']

In [37]:
mandats = df.drop_duplicates(subset= ["acteur_id_mandats"])[['acteur_id',
 'acteur_id_merge',
 'mandat_id',
 'groupe_id',
 'depute_nom_complet',
 'ident_civ_ANM',
 'ident_prenom_ANM',
 'ident_nom_ANM',
 'ident_male_ANM',
 'ident_year_birth_ANM',
 'profession_libellecourant_ANM',
 'election_lieu_departement_ANM',
 'election_lieu_numcirco_ANM',
 'mandat_legislature_ANM',
 'groupe_nb_membres',
 'groupe_codetype_ANO',
 'groupe_abrege_ANO',
 'groupe_libelle_ANO',
 'acteur_id_mandats',
 'mandat_id_mandats',
 'mandat_annee_debut_ANM',
 'mandat_annee_fin_ANM']]

In [38]:
votants = df.drop_duplicates(subset= ["acteur_id_mandats"])[['acteur_id',
 'acteur_id_merge',
 'mandat_id',
 'groupe_id',
 'depute_nom_complet',
 'ident_civ_ANM',
 'ident_prenom_ANM',
 'ident_nom_ANM',
 'ident_male_ANM',
 'ident_year_birth_ANM',
 'profession_libellecourant_ANM',
 'election_lieu_departement_ANM',
 'election_lieu_numcirco_ANM',
 'mandat_legislature_ANM',
 'groupe_nb_membres',
 'groupe_codetype_ANO',
 'groupe_abrege_ANO',
 'groupe_libelle_ANO',
 'acteur_id_mandats',
 'mandat_id_mandats',
 'mandat_annee_debut_ANM',
 'mandat_annee_fin_ANM']]

In [39]:
votants.shape[0]

1932

In [40]:
votants[['ident_nom_ANM', 'ident_prenom_ANM']].value_counts()

ident_nom_ANM     ident_prenom_ANM
Éblé              Vincent             1
Abad              Damien              1
Abadie            Caroline            1
Abba              Bérangère           1
Abeille           Laurence            1
                                     ..
Alaux             Sylviane            1
Ahamada           Saïd                1
Agresti-Roubache  Sabrina             1
Aeschlimann       Marie-Do            1
Adam              Patricia            1
Name: count, Length: 1931, dtype: int64

In [41]:
votants[['ident_nom_ANM', 'ident_prenom_ANM', 'mandat_annee_debut_ANM', 'mandat_annee_fin_ANM', 'groupe_abrege_ANO']].head()

,ident_nom_ANM,ident_prenom_ANM,mandat_annee_debut_ANM,mandat_annee_fin_ANM,groupe_abrege_ANO
37310,Bartolone,Claude,2012.0,2017.0,SRC
37311,Sirugue,Christophe,2012.0,2016.0,SRC
37312,Favennec-Bécot,Yannick,2025.0,NaN,UDI
37314,Dumont,Laurence,2017.0,2022.0,SRC
37316,Mazetier,Sandrine,2014.0,2017.0,SRC