In [2]:
import pandas as pd 
import os 
from pathlib import Path

In [9]:
corpus = pd.read_csv(Path(os.getcwd()) / "data/corpus_debats_2015_2025.csv", index_col=0)

In [10]:
corpus.head()

,attachmentUrl,dateSeance,dateParution,anneeParution,typeAssemblee,origine,legislature,session,nomSession,pathToFile,attachment_title,attachment_name,attachment_content_length,attachment_content_type,content
id,,,,,,,,,,,,,,,
ANSETEXT000053324357,AN_2025-142.pdf,1766448000000,1766534400000,2025,AN,Assemblée nationale,17,2025-2026,ordinaire,NaN,MasterAPP_AN_2025-142.pdf,NaN,100000.0,application/pdf,ASSEMBLÉE \nNATIONALE \n\nJOURNAL OFFICIEL DE ...
ANSETEXT000053324355,AN_2025-142_Bis.pdf,1766448000000,1766534400000,2025,AN_BIS,Assemblée nationale,17,2025-2026,ordinaire,NaN,MasterAPP_AN_2025-142 Bis.pdf,NaN,96278.0,application/pdf,ASSEMBLÉE \nNATIONALE \n\nJOURNAL OFFICIEL DE ...
ANSETEXT000053324356,AN_2025-141.pdf,1766016000000,1766102400000,2025,AN,Assemblée nationale,17,2025-2026,ordinaire,NaN,MasterAPP_AN_2025-141.pdf,NaN,100000.0,application/pdf,ASSEMBLÉE \nNATIONALE \n\nJOURNAL OFFICIEL DE ...
ANSETEXT000053324354,AN_2025-141_Bis.pdf,1766016000000,1766102400000,2025,AN_BIS,Assemblée nationale,17,2025-2026,ordinaire,NaN,MasterAPP_AN_2025-141 Bis.pdf,NaN,100000.0,application/pdf,ASSEMBLÉE \nNATIONALE \n\nJOURNAL OFFICIEL DE ...
ANSETEXT000053314220,AN_2025-140.pdf,1765929600000,1766016000000,2025,AN,Assemblée nationale,17,2025-2026,ordinaire,NaN,MasterAPP_AN_2025-140.pdf,NaN,100000.0,application/pdf,ASSEMBLÉE \nNATIONALE \n\nJOURNAL OFFICIEL DE ...

In [14]:
corpus[corpus["typeAssemblee"] == "AN"]["content"].iloc[32]

'ASSEMBLÉE \nNATIONALE \n\nJOURNAL OFFICIEL DE LA RÉPUBLIQUE FRANÇAISE \n\nXVIIe Législature  \n\nSESSION ORDINAIRE DE 2025-2026 \n\nSéances du jeudi 30 octobre 2025 \n\nCompte rendu intégral \n\nLes articles, amendements et annexes figurent dans le fascicule bleu ci-joint \n\nhttp://www.assemblee-nationale.fr \n\nAnnée 2025. – No 110 A.N. (C.R.) ISSN 2493-2086 Vendredi 31 octobre 2025 \n\n\n\nSOMMAIRE GÉNÉRAL  \n\n1re séance . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  8341 \n\n2e séance . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  8379 \n\n3e séance . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  8429      \n\n\n\nASSEMBLÉE \nNATIONALE \n\nJOURNAL OFFICIEL DE LA RÉPUBLIQUE FRANÇAISE \n\nSESSION ORDINAIRE DE 2025-2026 \n\n21e séance \n\nCompte rendu intégral \n\n1re séance du jeudi 30 octobre 2025 \n\nLes articles, amendements et annexes figurent dans le fascicule bleu ci-joint \n\nhttp://www.assemblee-nationale.fr    \n\nAnnée 2025. – No 110 [1] A.N. (C.R.) ISSN 2493-2086 Vendredi 31 octobre 2025 \n\n\n\nSOMMAIRE \n\nPRÉSIDENCE DE M. SÉBASTIEN CHENU \n\n1. Dénonciation des accords franco-algériens du 27 décembre \n1968 (p. 8343) \n\nDISCUSSION GÉNÉRALE (p. 8343) \nM. Guillaume Bigot \nMme Laure Miller \nM. Abdelkader Lahmar \nM. Laurent Lhardit \nM. Laurent Wauquiez \nMme Sabrina Sebaihi \nM. Bruno Fuchs \nM. Sylvain Berrios \nMme Soumya Bourouaha \nM. Matthieu Bloch \nM. Philippe Bonnecarrère \nM. Laurent Panifous, ministre délégué chargé des relations \n\navec le Parlement \n\nEXPLICATIONS DE VOTE (p. 8355) \nM. Guillaume Bigot (RN) \nMme Laure Miller (EPR) \nM. Bastien Lachaud (LFI-NFP) \nM. Laurent Lhardit (SOC) \nM. Éric Pauget (DR) \nMme Sabrina Sebaihi (EcoS) \nM. Bruno Fuchs (Dem) \nM. Sylvain Berrios (HOR) \nM. Laurent Mazaury (LIOT) \nMme Elsa Faucillon (GDR) \nM. Éric Ciotti (UDR) \n\nVOTE SUR LA PROPOSITION DE RÉSOLUTION (p. 8361) \n\nRappels au règlement (p. 8361) \nM. Alexis Corbière \nMme Mathilde Panot \n\nM. Matthias Tavel \n\nSuspension et reprise de la séance (p. 8362) \n2. Rétablissement du délit de séjour irrégulier (p. 8362) \n\nPRÉSENTATION (p. 8362) \nMme Sylvie Josserand, rapporteure de la commission des lois \n\nconstitutionnelles, de la législation et de l’administration \ngénérale de la République \n\nM. Laurent Nuñez, ministre de l’intérieur \nM. Florent Boudié, président de la commission des lois \n\nconstitutionnelles, de la législation et de l’administration \ngénérale de la République \n\nDISCUSSION GÉNÉRALE (p. 8366) \nM. Jordan Guitton \nM. Thomas Cazenave \nMme Elsa Faucillon \nM. Paul Christophle \nM. Éric Pauget \nMme Léa Balage El Mariky \nM. Éric Martineau \nM. Xavier Albertini \nMme Constance de Pélichy \nMme Gabrielle Cathala \nMme Hanane Mansouri \nM. Philippe Bonnecarrère \n\nRappels au règlement (p. 8375) \nMme Léa Balage El Mariky \nMme Gabrielle Cathala \nMme Marine Le Pen \nM. Pierre Cazeneuve \nMme Hanane Mansouri \n\nREPRISE DE LA DISCUSSION (p. 8376) \nMme Sylvie Josserand, rapporteure \nM. Florent Boudié, président de la commission des lois \n\n3. Ordre du jour de la prochaine séance (p. 8378) \n\n8342 ASSEMBLÉE NATIONALE – 1re SÉANCE DU 30 OCTOBRE 2025 \n\n\n\nCOMPTE RENDU INTÉGRAL \n\nPRÉSIDENCE DE M. SÉBASTIEN CHENU \n\nvice- président \n\nM. le président. La séance est ouverte. \n(La séance est ouverte à neuf heures.) \n\n1 \n\nDÉNONCIATION DES ACCORDS \nFRANCO-ALGÉRIENS  \n\nDU 27 DÉCEMBRE 1968 \n\nDiscussion d’une proposition de résolution \n\nM. le président. L’ordre du jour appelle la discussion, en \napplication de l’article 34-1 de la Constitution, de la propo\nsition de résolution de M. Guillaume Bigot, de Mme Marine \nLe Pen et des autres membres du groupe Rassemblement \nnational visant à dénoncer les accords franco-algériens du \n27 décembre 1968 (no 1778). \n\nDISCUSSION GÉNÉRALE \n\nM. le président. La parole est à M. Guillaume Bigot. \nM. Guillaume Bigot. Imaginez un contrat : un contrat qui \n\nvous lie à un partenaire qui ne respecte aucun de ses engage\nments ; un contrat où vous devez tout, et votre partenaire ne \ndoit rien ; mais un contrat que vous continuez pourtant à \nrespecter scrupuleusement, dans l’esprit comme dans la \nlettre. Ce contrat existe, c’est l’accord franco-algérien du \n27 octobre 1968. \n\nL’excellent rapport d’information que notre collègue \nCharles Rodwell a consacré à cet accord évoque un « véritable \nstatut » de l’Algérien en France, extrêmement dérogatoire au \ndroit commun. C’est d’abord vrai en matière de prestations \nsociales. Un étranger, selon le droit commun, doit résider \ncinq ans en France pour toucher le RSA, les allocations \nfamiliales ou la prime d’activité ; pour un Algérien, cette \nexigence disparaît. Un étranger doit résider dix ans en \nFrance avant de bénéficier du minimum vieillesse ; un \nAlgérien y a droit au bout d’un an. \n\nCe régime extrêmement dérogatoire concerne aussi le \nfranchissement des frontières : les Algériens peuvent \ns’absenter trois ans de France sans perdre leur titre de \nséjour, contre six mois pour les autres étrangers. On peut \nretirer un titre de séjour à un étranger qui trouble l’ordre \npublic ou qui pratique la polygamie ; ce n’est pas possible \npour un Algérien. \n\nAutre dérogation : le regroupement familial. Un Algérien \npeut faire venir sa famille en ne gagnant qu’un smic – en \nintégrant les aides sociales –, là où le droit commun exige \nbien davantage des autres étrangers. Plus extravagant encore, \ndans certains domaines, l’accord de 1968 avantage les \nAlgériens par rapport aux nationaux. Par exemple, \nlorsqu’un étudiant algérien veut ouvrir un commerce, l’admi\nnistration n’a pas le droit de vérifier la réalité de l’entreprise \ncréée, alors qu’elle le peut pour un étudiant français. \n\nOn nous dira que c’est le prix à payer pour l’intégration, \nmais le rapport Rodwell démontre le contraire. Le taux de \nchômage des Algériens est plus du double de celui de l’Hexa\ngone. Le taux d’emploi des immigrés algériens est inférieur de \n14 points à la moyenne nationale. Près de 40 % des Algériens \nde 15 ans et plus ne sont ni en emploi, ni en études. Ils sont \nsimplement inactifs, vivant pour beaucoup des aides sociales. \n\nM. Sébastien Delogu. Mais bien sûr ! \nM. Guillaume Bigot. Les ressortissantes algériennes sont \n\ninactives à plus de 50 %. \nAvec le contrat de 1968, nous avons non seulement créé \n\nune filière d’immigration à part entière, mais aussi engendré \ndes trappes à pauvreté intergénérationnelle – le taux d’emploi \ndes descendants d’immigrés algériens est encore plus bas que \ncelui de leurs parents. C’est une véritable pompe aspirante \npour l’immigration, et une pompe expirante pour nos \nfinances publiques. \n\nEn outre, ce régime dérogatoire, maintenu par les accords \nde 1968, produit des effets encore plus choquants. Par cet \naccord, la France accepte la kafala, une norme du droit \nislamique qui facilite le regroupement familial en plaçant \ndes enfants algériens sous l’autorité de grands-parents ou \nd’oncles et de tantes, qui peuvent les faire venir. \n\nComment pouvons-nous d’un côté interdire les signes \nreligieux à l’école et de l’autre appliquer la kafala dans \nnotre droit pour complaire à un autre État ? Cette \nanomalie bafoue la laïcité. \n\nM. Sébastien Delogu. Ça n’a rien à voir ! \nM. Guillaume Bigot. Cela a tout à voir ! Soit vous êtes \n\nsincèrement laïques et vous votez pour abroger ce texte qui \nne l’est pas, soit vous refusez de l’abroger, et dans ce cas, ne \nvenez plus jamais nous parler de laïcité. (Applaudissements sur \nles bancs des groupes RN et UDR.) \n\nM. Boris Vallaud. Racisme ! \nM. Guillaume Bigot. Sur le plan sécuritaire, le déséquilibre \n\ninduit par l’accord de 1968 est tout aussi manifeste. En dix \nans, le nombre d’Algériens dans nos prisons est passé de \nmoins de 2 000 à plus de 4 000, soit une hausse de \n177 % ; autant de criminels et de délinquants qui devraient, \nune fois leur peine purgée, être renvoyés dans leur pays – c’est \nlogique. \n\nMais il n’en est rien. Pourquoi ? Parce qu’Alger refuse de \ndélivrer les laissez-passer consulaires et de reprendre ses \npropres ressortissants. Le terroriste de l’attentat de \n\nASSEMBLÉE NATIONALE – 1re SÉANCE DU 30 OCTOBRE 2025 8343 \n\n\n\nMulhouse : il a été visé par quatorze procédures d’expulsion, \nmais il y a eu quatorze refus de l’Algérie. Un Algérien \ncondamné pour violences conjugales : il est protégé par \nl’accord, donc inexpulsable. La meurtrière de la petite \nLola : elle est, elle aussi, placée, sous obligation de quitter \nle territoire français (OQTF), obligation non exécutée. \n\nAlors, que faire ? Continuer à verser 2 milliards d’euros par \nan d’aides et de prestations sociales aux Algériens, de manière \ndérogatoire, alors que leur pays refuse toute réciprocité ? \nContinuer à espérer la clémence d’un régime qui a injuste\nment emprisonné nos ressortissants, Boualem Sansal et \nChristophe Gleizes ? \n\nC’est le chantage qu’Alger a exercé sur le Quai d’Orsay, \nlequel a supplié nos alliés de l’UDR de retirer le texte de leur \nniche le 26 juin dernier. Pour quel résultat ? Mon ami \nBoualem a été condamné encore plus durement ! (Applaudis\nsements sur les bancs du groupe RN et sur quelques bancs du \ngroupe UDR.) \n\nNous ne devons plus tergiverser ; il faut adopter cette \nproposition de résolution pour enjoindre au gouvernement \nde dénoncer l’accord franco-algérien de 1968. \n\nPour vous en convaincre, permettez-moi de répondre à une \ncritique formulée, sur les réseaux sociaux, par Charles \nRodwell, l’auteur du rapport d’information que j’évoquais \nil y a un instant. Notre collègue prétend que, en prévoyant de \nn’appliquer que le droit commun des étrangers aux Algériens, \nnous allons rétablir la libre circulation entre la France et \nl’Algérie prévue par les accords de 1962. C’est le fameux \nchantage : si on dénonce l’accord de 1968, les dispositions \ndes accords d’Évian de 1962 s’appliqueront. \n\nNotre collègue tente même de nous effrayer en brandissant \nle spectre d’un déferlement migratoire sur notre pays. En \nFrance, la population immigrée a augmenté en un an autant \nque durant les trois années précédentes, et elle affiche une \nhausse vingt-cinq fois supérieure à la moyenne des \nannées 1990. M. Rodwell ne manque donc pas d’air : il \nagite la menace d’un déferlement qu’Emmanuel Macron \norchestre depuis 2017 ! (M. Boris Vallaud s’exclame.) \n\nMais surtout, cette menace infondée révèle que le macro\nnisme est une baudruche, à la fois technique et intellectuelle. \nL’argument de la libre circulation automatique est un \népouvantail juridique. En droit international, la dénonciation \nd’un traité bilatéral ne ressuscite pas automatiquement les \ntraités antérieurs lorsque que ces derniers ont été remplacés \nou complétés – comme ce fut le cas des accords d’Évian de \n1962, remplacés par celui de 1968. \n\nC’est précisément ce que prévoit l’article 59 de la Conven\ntion de Vienne : lorsqu’un traité antérieur est réputé avoir été \nremplacé par un traité postérieur plus contraignant, le \npremier ne revient pas. \n\nEn outre, l’accord de 1968 n’a absolument aucune raison \nd’être perpétuel – il n’avait pas vocation à l’être. L’immigra\ntion est un sujet qui peut évoluer dans le temps. Cet accord a \nété conclu six ans après l’indépendance de l’Algérie, à une \népoque de plein-emploi et de prospérité ; ce n’est évidem\nment plus le cas. \n\nAjoutons que, selon le principe pacta sunt servanda, la non- \napplication par Alger de ses engagements nous donne le droit \nde renégocier l’accord. Si l’Algérie refuse un nouvel accord, \nalors c’est le droit commun qui s’appliquera. \n\nEn dénonçant cet instrument désuet, nous appliquerons le \ndroit commun de la République, celui qui encadre l’entrée, le \nséjour et l’établissement des ressortissants de pays tiers à \nl’Union européenne. \n\nNotre démarche est soutenue par 66 % de nos compa\ntriotes. Les Français nous regardent, et ils attendent de nous \ncohérence et courage. \n\nD’ailleurs, n’exagérons pas la dose de courage requise : il \ns’agit simplement de sortir d’un mélange de torpeur et de \nmauvaise conscience. Au fond, l’Algérie a beaucoup plus à \nperdre que nous dans cette confrontation ; avec un PIB vingt \nfois inférieur au nôtre, elle ne peut tout simplement pas se \npasser des visas que nous accordons à ses élites, ni des flux \nfinanciers qui relient nos deux pays – se fâcher avec la France \naurait un coût bien plus dirimant pour Alger que pour Paris. \n\nIl nous faut donc dénoncer cet accord,… \nM. Pierre Pribetich. Non ! \nM. Guillaume Bigot. …et nous devons le faire non par \n\nhostilité envers le peuple algérien,… \nM. Boris Vallaud. Ah bon ? \nM. Pierre Pribetich. À peine… \nM. Guillaume Bigot. …qui souffre lui aussi du régime \n\nd’Alger, mais au contraire parce que les Algériens ne \ndoivent plus être des étrangers à part ; ils doivent devenir \ndes étrangers à part entière. Il ne doit y avoir en France \nqu’une seule catégorie d’étrangers hors Union européenne, \négaux en droits et en devoirs. \n\nL’Algérie française, c’est fini ! (Applaudissements sur les bancs \ndu groupe RN et sur quelques bancs du groupe UDR.) \n\nM. Pierre Pribetich. C’était vous ! \nM. Guillaume Bigot. Soixante-trois ans après l’indépen\n\ndance, il est temps d’en accepter les conséquences, en \ntraitant notre ancienne colonie comme tous les autres pays \n– ni mieux, ni moins bien, sans dérogation. (Applaudissements \nsur les bancs des groupes RN et UDR.) \n\nM. Pierre Pribetich. C’était vous, l’Algérie française ! \nM. Guillaume Bigot. Cette dénonciation n’est pas une fin \n\nen soi ; cela envoie le signal que notre pays cesse de courber \nl’échine, rompt avec une mauvaise conscience malsaine et \nveut normaliser ses relations avec l’Algérie. \n\nÀ cet égard, assumer le bras de fer est indispensable pour \nrétablir l’équilibre : plus aucun visa tant que nos ressortissants \nBoualem Sansal et Christophe Gleizes ne seront pas libérés, \nou plutôt un visa par OQTF exécutée – donnant-donnant, \nentre égaux. (M. Boris Vallaud s’exclame.) \n\nJe vous entends déjà dire populisme, démagogie, effet de \ntribune. Vous avez tort. \n\nM. Sébastien Delogu. Racistes ! (Protestations sur plusieurs \nbancs du groupe RN.) \n\nM. Guillaume Bigot. C’est vous ! C’est vous qui adaptez \nvotre propagande selon l’origine de nos concitoyens ! \n\nLa France doit se respecter, en se faisant respecter, et en \nfaisant respecter le droit international. \n\nPour finir, je m’adresse à ceux de mes collègues qui, tout en \nétant secrètement d’accord avec nous, hésitent à voter avec \nnous. \n\nM. Pierre Pribetich. Nous ne sommes pas d’accord avec \nvous ! \n\n8344 ASSEMBLÉE NATIONALE – 1re SÉANCE DU 30 OCTOBRE 2025 \n\n\n\nM. Guillaume Bigot. Collègues Républicains, voterez-vous \npour cette résolution, en cohérence avec les positions du \nprésident Bruno Retailleau, qui a rappelé l’impérieuse néces\nsité de dénoncer l’accord il y a deux semaines encore ? \n\nM. Jean-Pierre Vigier et M. Éric Pauget. Oui ! \n\nM. Pierre Pribetich. Il n’est plus là ! \n\nM. Guillaume Bigot. Collègues Démocrates, suivrez-vous le \nsouhait de votre président François Bayrou, qui admettait le \n26 février dernier la nécessité de remettre en cause l’accord ? \n\nCollègues du groupe Horizons, allez-vous désavouer votre \ncandidat à la présidentielle Édouard Philippe, qui appelait en \nmars dernier à revenir sur les accords de 1968 ? \n\nCollègues macronistes, vos votes contrediront-ils les propos \ntenus par Gabriel Attal le 10 janvier 2025 – « La France doit \navoir le courage de […] mettre un terme à l’accord franco- \nalgérien de 1968 […]. » « L’heure de la fermeté a sonné », \najoutait-il. \n\nM. le président. Merci de bien vouloir conclure. \n\nM. Guillaume Bigot. Oui, l’heure de la fermeté… (Le temps \nde parole étant écoulé, M. le président coupe le micro de \nl’orateur. – Les députés des groupes RN et UDR se lèvent et \napplaudissent ce dernier.) \n\nM. le président. La parole est à Mme Laure Miller. \n\nMme Laure Miller. Il m’est impossible de commencer sans \navoir une pensée pour Boualem Sansal, honteusement \nenfermé depuis le 16 novembre 2024, et dont nous deman\ndons la libération immédiate, ainsi que celle de Christophe \nGleizes. \n\nNous sommes réunis pour débattre d’un sujet grave et \nsensible, qui engage bien plus que notre politique migratoire : \ncelui de nos relations avec l’Algérie, plus particulièrement de \nl’accord franco-algérien de 1968, dont les effets suscitent de \nnombreuses critiques au-delà des clivages partisans. \n\nCe débat, parce qu’il touche aux relations entre nos deux \npeuples, doit être abordé avec lucidité, sans tabou et sans \nexcès. La position du groupe Ensemble pour la République \nest connue et claire : oui, l’accord franco-algérien de 1968 \npose plusieurs problèmes. (« Ah ! » sur quelques bancs du \ngroupe RN.) \n\nD’abord, un problème d’égalité de traitement entre ressor\ntissants étrangers résidant sur le territoire français. L’applica\ntion des accords franco-algériens crée une inégalité injustifiée \nen accordant aux ressortissants algériens des avantages \ndérogatoires qui ne reposent plus sur aucune justification \nobjective – ni juridique, ni diplomatique. \n\nUn député du groupe RN. C’est bien ! \n\nMme Laure Miller. Comme l’a démontré le rapport de \nCharles Rodwell, le texte de 1968, ses avenants successifs \net une jurisprudence constante ont progressivement \ninstauré des droits beaucoup plus favorables pour les ressor\ntissants algériens – je pense en particulier à la carte de séjour \nde dix ans, de plein droit, et dont le renouvellement est \nautomatique. \n\nDans le même temps, la jurisprudence a affaibli certains \ngarde-fous du droit commun : elle a notamment considéré \nqu’aucune disposition ne permettait de retirer cette carte à \ndes ressortissants algériens pour des motifs d’ordre public. \n\nAutrement dit, même dans des situations où un retrait de \ntitre serait légitime, l’administration est contrainte d’engager \nune procédure d’expulsion, beaucoup plus lourde \n– beaucoup plus lente – et réservée aux cas les plus graves. \n\nPlus largement, l’ensemble des mécanismes de contrôle \nclassiques – examen des ressources, durée de présence, condi\ntions d’entrée, exigence d’intégration – ont été progressive\nment affaiblis par la manière dont cet accord est aujourd’hui \nappliqué. \n\nParallèlement, l’accord produit un effet paradoxal : il prive \nces mêmes ressortissants de certains avantages du droit \ncommun qui leur seraient pourtant plus favorables – je \npense notamment au passeport talent. \n\nNotre position est claire : un ressortissant algérien ne doit \navoir ni plus, ni moins, de droits qu’un autre étranger non \ncommunautaire. Il y va du principe même d’égalité devant la \nloi. \n\nM. Laurent Wauquiez. Très bien. \n\nMme Laure Miller. Au-delà de ces anomalies juridiques, \nl’accord a également un coût significatif pour nos finances \npubliques. Le rapport Rodwell estime entre 200 et \n300 millions d’euros par an le surcoût administratif et \njuridictionnel lié aux facilités d’accès et de maintien sur le \nterritoire. À cela s’ajoute un surcoût social estimé entre 1,5 et \n2 milliards d’euros par an, en raison de structures familiales \nplus dépendantes des minima sociaux et des prestations telles \nque le RSA, la prime d’activité, l’allocation de solidarité aux \npersonnes âgées (Aspa) ou encore l’allocation aux adultes \nhandicapés (AAH). \n\nPour toutes ces raisons, nous sommes favorables à la remise \nen cause de cet accord. (« Ah ! » 

In [5]:
%pip install ijson

Collecting ijson
  Downloading ijson-3.5.0-cp311-cp311-win_amd64.whl.metadata (24 kB)
Downloading ijson-3.5.0-cp311-cp311-win_amd64.whl (55 kB)
Installing collected packages: ijson
Successfully installed ijson-3.5.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\rorod\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [6]:
# Si besoin: %pip install ijson
import ijson
from itertools import islice

json_path = Path(os.getcwd()) / "data/liste_debats_2015_2025.json"

with open(json_path, "rb") as f:
    premiers_objets = list(islice(ijson.items(f, "item"), 10))

metadata_debats = pd.DataFrame(premiers_objets)
metadata_debats.head()

,id,idEli,origine,dateSeance,dateParution,anneeParution,typeAssemblee,legislature,numeroParution,nomSession,session,attachmentUrl,data,refInjection,idTechInjection,displaySize,pathToFile,attachment_info
0,ANSETEXT000053324357,eli/ancr/2025/142,Assemblée nationale,1766448000000,1766534400000,2025,AN,17,142,ordinaire,2025-2026,AN_2025-142.pdf,JVBERi0xLjYKJeTjz9IKOSAwIG9iago8PC9TdWJ0eXBlL0...,IG-20260113,ANSETEXT000053324357,None,None,"{'title': 'MasterAPP_AN_2025-142.pdf', 'name':..."
1,ANSETEXT000053324355,eli/ancr/2025/142_bis,Assemblée nationale,1766448000000,1766534400000,2025,AN_BIS,17,142,ordinaire,2025-2026,AN_2025-142_Bis.pdf,JVBERi0xLjYKJeTjz9IKOSAwIG9iago8PC9TdWJ0eXBlL0...,IG-20260113,ANSETEXT000053324355,None,None,"{'title': 'MasterAPP_AN_2025-142 Bis.pdf', 'na..."
2,ANSETEXT000053324356,eli/ancr/2025/141,Assemblée nationale,1766016000000,1766102400000,2025,AN,17,141,ordinaire,2025-2026,AN_2025-141.pdf,JVBERi0xLjYKJeTjz9IKOSAwIG9iago8PC9TdWJ0eXBlL0...,IG-20260113,ANSETEXT000053324356,None,None,"{'title': 'MasterAPP_AN_2025-141.pdf', 'name':..."
3,ANSETEXT000053324354,eli/ancr/2025/141_bis,Assemblée nationale,1766016000000,1766102400000,2025,AN_BIS,17,141,ordinaire,2025-2026,AN_2025-141_Bis.pdf,JVBERi0xLjYKJeTjz9IKOSAwIG9iago8PC9TdWJ0eXBlL0...,IG-20260113,ANSETEXT000053324354,None,None,"{'title': 'MasterAPP_AN_2025-141 Bis.pdf', 'na..."
4,ANSETEXT000053314220,eli/ancr/2025/140,Assemblée nationale,1765929600000,1766016000000,2025,AN,17,140,ordinaire,2025-2026,AN_2025-140.pdf,JVBERi0xLjYKJeTjz9IKOSAwIG9iago8PC9TdWJ0eXBlL0...,IG-20260113,ANSETEXT000053314220,None,None,"{'title': 'MasterAPP_AN_2025-140.pdf', 'name':..."